# Generated by Django 5.0.5 on 2024-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chest_x_ray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='x_ray')),
                ('result_pred', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
