# Generated by Django 5.0.5 on 2024-05-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_x_ray'),
    ]

    operations = [
        migrations.DeleteModel(
            name='X_ray',
        ),
    ]
